### ISSUE TITLE
Printed DO without postal code.

### ISSUE THREAD

**Issue by IM-HOLDINGS** [IM-HOLDINGS/infolog_request#1]
![image](https://user-images.githubusercontent.com/44354801/47340028-95869680-d6cf-11e8-901e-1a1f328fe57b.png)

**Comment by deanliew** [comment]
Will investigate and revert.

**Comment by deanliew** [comment]
Program fixed and please test in training env.

**Comment by deanliew** [comment]
@deanliew-imf Program fixed and please test.

**Comment by deanliew** [comment]
@deanliew-imf test please

**Comment by IM-HOLDINGS** [comment]
Test ok .. Can closed/
